replicaCount: 1
ingress:
  enabled: true
  host: preview.devhub.local
env:
  LOG_LEVEL: debug
extraLabels:
  devhub.io/env: preview
resources:
  requests:
    cpu: 25m
    memory: 48Mi
  limits:
    cpu: 100m
    memory: 128Mi
image:
  tag: 7ef6719
